[package]
name = "mersennet-node"
version = "0.7.0"
authors = ["Rodolfo Cova @rodaemonic"]
edition = "2024"

[features]
default = []
prover = ["mersennet/prover", "mersennet-rpc/prover", "mersennet-zkp/prover"]
sp1 = ["mersennet/sp1", "mersennet-rpc/sp1", "mersennet-zkp/sp1"]

[[bin]]
name = "mersennet"
path = "src/bin/mersennet.rs"

[[bin]]
name = "genesis"
path = "src/bin/genesis.rs"

[[bin]]
name = "faucet"
path = "src/bin/faucet.rs"

[[bin]]
name = "loadtest"
path = "src/bin/loadtest.rs"

[[bin]]
name = "stresstest"
path = "src/bin/stresstest.rs"

[[bin]]
name = "migrate-genesis"
path = "src/bin/migrate_genesis.rs"

[dependencies]
mersennet = { path = "../core" }
mersennet-network = { path = "../network" }
mersennet-rpc = { path = "../rpc" }
anyhow = "1.0"
hex = "0.4"
k256 = { version = "0.13", default-features = false, features = ["ecdsa", "sha256", "std"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny_http = "0.12"
ureq = "2.9"
revm = { version = "12", default-features = false, features = ["std", "serde", "c-kzg"] }
ctrlc = "3.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
metrics = "0.19"
tempfile = "3.10"
sha3 = "0.10"
mersennet-zkp = { path = "../zkp" }
